sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gz12345678

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx394bab65a441816f
    secret: 09eca21ba606702f3ae3ceb10d41c64e


